### ISSUE TITLE
Please add LendingTree Filter Name to Mortech Integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-mortech#14]
We have a current customer (https://activeprospect.zendesk.com/agent/tickets/6165) that needs to route the data from Filter Name into Filter ID for Mortech. 

Filter Name is not in the integration. 

But my next question is, once this is added, can I do the following:

Receive FilterName from LT --> Normalize the data in LCN to lendingtree.filter_name --> Send to Mortech as Filter ID.

Please LMK.

**Comment by alexkwolfe** [comment]
The [filter name](https://github.com/activeprospect/leadconduit-integration-lendingtree/blob/b7a848830591c5b2399cc69c11461446ff513039/src/unified.coffee#L61) is already supported by the LendingTree integration.

The [filter id](https://github.com/activeprospect/leadconduit-integration-mortech/blob/c8972f43ed8adaee8e7b947cef9f9ec69839ed4f/src/outbound.coffee#L83) is already supported by the Mortech integration.

This problem can be solved using a mapping on the Mortech integration.

**Comment by kcaponeAP** [comment]
Okay, I tried this and it did not work as expected. I am waiting on confirmation that filter_id (in Mortech) is the correct system name. However, upon POST to Mortech, I got:

".....&PropertyCounty=Dallas&LTFilterID=" 

Not sure where LTFilterID is coming from

https://next.leadconduit.com/events/54ca971c6c817b5f02693900

![screen shot 2015-01-29 at 2 39 32 pm](https://cloud.githubusercontent.com/assets/8238417/5965824/a81ee682-a7c4-11e4-8efe-f1c67927c72c.png)

**Comment by zalary** [comment]
the Mortech docs we have on file indicate the only filter field they support is named LTFilterID.  If that's not the case and we should actually be using a differently named field, can we get updated docs from them? (and

**Comment by kcaponeAP** [comment]
dang... now i see that it could  be:

lead.lendingtree.filter_routing_id

I am getting confused in certain cases when to use stuff like "lead.lendingtree.filter_routing_id" or "mortech.field_name"

**Comment by kcaponeAP** [comment]
k that worked. TYVM.

**Comment by alexkwolfe** [comment]
@justinwinslow, thought you might like to peek at this.

**Comment by justinwinslow** [comment]
I'm not sure I understand what is happening.

**Comment by alexkwolfe** [comment]
She wanted to map the LendingTree Filter Name to the Filter ID field being sent to Mortech. This is fully supported via the UI but unclear how it works.

**Comment by justinwinslow** [comment]
Wasn't it unclear what the correct mortech field name was?

**Comment by alexkwolfe** [comment]
I'm not exactly sure. That seems to have been one of the issues.

**Comment by cgrayson** [comment]
@kcaponeAP it's named `lendingtree.filter_routing_id` because that's where we thought the data would be coming from. That is, if this customer had wanted the LendingTree filter _id_ to go through to Mortech, it would have Just Worked™, with no mapping, as automatically as `first_name` is sent as `FirstName`. 

It seems odd to me that this customer wants one LendingTree filter-related thing (name) to be sent to as if it were a different filter-related thing (id). If we're sure that's correct, and if it's a common thing for leads sent to Mortech, it could be changed in this integration. In other words, the integration could set `LTFilterID` to `lendingtree.filter_routing_id`, or if that's not present, to `lendingtree.filter_name`.

**Comment by kcaponeAP** [comment]
This sounds like an edge case. At this time, I have not one other customer who is using Mortech and LT. I'll keep this one in mind for the next use case of LT / Mortech. I don't see any changes necessary ATM. Do you?

**Comment by cgrayson** [comment]
I'll defer to Zalary, but if this is the one & only, then perhaps the changes in PR #12 weren't the right fix for issue #11.

**Comment by zalary** [comment]
I won't overly defend by position because even though issue #11  starts off talking about filter_id it does eventually say "Filter_ID is always Filter_Name for LendingTree leads"

However, the docs we have from Mortech contradict this 

![screen shot 2015-01-30 at 8 38 13 am](https://cloud.githubusercontent.com/assets/338654/5977236/609ab8b2-a85b-11e4-8303-ba7a476e3790.png)

That said, if this particular use case is not an exception, but the rule and Mortech will accept a string in that field, then we should probably update this.

**Comment by alexkwolfe** [comment]
It sounds like Karalyn is saying that a mapping will work fine. Or am I missing something?

**Comment by kcaponeAP** [comment]
The mapping works fine. 

That being said, I don't think we have enough customers using a LT/Mortech workflow to really have a sampling of use cases to understand how the customers want the data.

**Comment by alexkwolfe** [comment]
One bit of information on this. LT shortform does not provide filter ID. This might be why the customer is asking for us to put filter name in the mortech filter ID field.

**Comment by kcaponeAP** [comment]
That is very interesting observation. I'll keep this in mind for further LT
integration questions.

**Comment by zalary** [comment]
I'm curious as the whether Mortech actually accepts the full name string here (is there really a 7 char limit)?
