### ISSUE TITLE
Email Status / Phone Status

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-mortech#15]
Please create the fields email_status, phone_status and phone_value in Mortech.

We are instructing customers using Mortech to have Mortech map these in their custom setups. 

This is needed info to pass TeleSign and BriteVerify data. We wanted to keep it vendor-free, hence the generic names of fields.

**Comment by zalary** [comment]
should we create sensible defaults here?  like setting email_status to briteverify.email.status if that value is available?

I suppose this could get trickier as we add on enhancement services, but it kind of stinks to create a field that a user has to know what to do with instead of having it 'just work'  

cc: @alexkwolfe @cgrayson

**Comment by alexkwolfe** [comment]
IMO, rather than relying on Mortech (and other CRMs) to know about every different enhanchement service, each enhancement service should instead populate a common shared variable using a standard value (i.e. `email_status=invalid` or `email_status=valid`). There is no mechanism that we could currently use to make this happen so the lead handler would have to change.

**Comment by alexkwolfe** [comment]
In the meantime, it would be fine to add these to this integration under the presumption that users would have to map them until such time as they are made available automatically.

**Comment by cgrayson** [comment]
I was thinking that this integration including BriteVerify et al (if present) would be ok. That would put us on the hook to keep this updated with future providers of such statuses, which is a little bit of a drag but not terrible imho. 

But there's another possible issue, and it's shared by Alex's suggestion to have enhancement services set the value: what about ordering? What if a flow includes more than one service that can set `email_status`? Last one wins, maybe? 

Making the flow configurer map it is maybe extra work, but if nothing else puts them in full control.

**Comment by cgrayson** [comment]
> There is no mechanism that we could currently use to make this happen so the lead handler would have to change.

What if there were simply standard fields for these? Include them in the enhancement services' response variables and they'd be automatically added to the flow. Naming might be awkward… could namespace them? E.g., `leadconduit.email_status`?

**Comment by alexkwolfe** [comment]
Yes. This is what I was thinking. They wouldn't be fields in the leadconduit-fields module, but would rather be data that gets appended to a lead in a standard variable name. But again, this is something that would need to be handled in a special way by the handler. Currently, all appended data is automatically namespaced per the entity name (e.g. `briteverify.email.status`).
