### ISSUE TITLE
Please update deprecated fields / Mortech

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-mortech#17]
Please update:

mortgage.application.credit_rating --> credit_rating
mortgage.application.bankruptcy --> 
mortgage.bankruptcy.was_discharged

**Comment by zalary** [comment]
did you mean for bankruptcy to map to was_declared?  
the option for discharged is discharged_months_ago and is a range.

**Comment by kcaponeAP** [comment]
Correct. My mistake. mortgage.bankruptcy.was_declared is what it should be.

**Comment by kcaponeAP** [comment]
Application Credit Rating &
Application Bankruptcy are still listed as deprecated in the Mortech integration. Can these be updated? @alexj

**Comment by alexj** [comment]
I would expect so to avoid these sticking around forever. Any blockers from the tech/data side?

**Comment by zalary** [comment]
do we have anyone currently delivering leads to Mortech?  

I ask because outbound integrations can be tricker to update than inbound ones. We need to make sure no sources are sending through deprecated fields and no inbound data is mapped to a deprecated field in a flow, or that data will no longer be passed to the endpoint.

**Comment by kcaponeAP** [comment]
No ma'am :)

I checked the 5 active Mortgage flows. Nada.

**Comment by zalary** [comment]
ty
